import type { Application } from '@atx/application';
import {
  AdminClaimReview,
  AdminConceptCreate,
  AdminVerificationDecision,
  AuditEventRecord,
  ClaimView,
  InvitationRecord,
  IssuedInvitation,
  OfferingRecord,
  OrganizationRecord,
  OrganizationRef,
  PlatformInvitationCreate,
  Uuid,
} from '@atx/contracts';
import { z } from 'zod';
import { type AnyRouteSpec, defineRoute } from '../http/route';

/** Platform administration. Every use case re-checks the platform_admin role. */
export const adminRoutes = (app: Application): AnyRouteSpec[] => [
  defineRoute({
    method: 'POST',
    url: '/v1/admin/invitations',
    operationId: 'adminCreateInvitation',
    summary: 'Invite a person to register (pilot sign-up invitation); returns the secret link once',
    tags: ['admin'],
    auth: 'required',
    body: PlatformInvitationCreate,
    response: IssuedInvitation,
    status: 201,
    handler: async ({ body, ctx }) => app.invitations.createPlatformInvitation(ctx, body.email),
  }),
  defineRoute({
    method: 'GET',
    url: '/v1/admin/invitations',
    operationId: 'adminListInvitations',
    summary: 'Platform sign-up invitations and their status',
    tags: ['admin'],
    auth: 'required',
    response: z.object({ items: z.array(InvitationRecord) }),
    handler: async ({ ctx }) => ({ items: await app.invitations.listPlatformInvitations(ctx) }),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/admin/invitations/:invitationId/revoke',
    operationId: 'adminRevokeInvitation',
    summary: 'Revoke a pending sign-up invitation',
    tags: ['admin'],
    auth: 'required',
    params: z.object({ invitationId: Uuid }),
    response: z.object({ revoked: z.literal(true) }),
    handler: async ({ params, ctx }) => {
      await app.invitations.revokePlatformInvitation(ctx, params.invitationId);
      return { revoked: true as const };
    },
  }),
  defineRoute({
    method: 'GET',
    url: '/v1/admin/verification-queue',
    operationId: 'adminVerificationQueue',
    summary: 'Organizations awaiting verification',
    tags: ['admin'],
    auth: 'required',
    response: z.object({
      items: z.array(
        OrganizationRef.extend({ kind: z.string(), website: z.string().nullable(), requestedAt: z.string() }),
      ),
    }),
    handler: async ({ ctx }) => ({ items: await app.admin.verificationQueue(ctx) }),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/admin/organizations/:orgId/verification',
    operationId: 'adminSetVerification',
    summary: 'Verify, reject or suspend an organization',
    tags: ['admin'],
    auth: 'required',
    params: z.object({ orgId: Uuid }),
    body: AdminVerificationDecision,
    response: OrganizationRecord,
    handler: async ({ params, body, ctx }) =>
      app.admin.setOrganizationVerification(ctx, params.orgId, body.state, body.reason),
  }),
  defineRoute({
    method: 'GET',
    url: '/v1/admin/claims/review-queue',
    operationId: 'adminClaimQueue',
    summary: 'Published claims awaiting platform evidence review',
    tags: ['admin'],
    auth: 'required',
    response: z.object({ items: z.array(ClaimView) }),
    handler: async ({ ctx }) => ({ items: await app.admin.claimReviewQueue(ctx) }),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/admin/claims/:claimId/review',
    operationId: 'adminReviewClaim',
    summary: 'Record a platform evidence review outcome for a claim',
    tags: ['admin'],
    auth: 'required',
    params: z.object({ claimId: Uuid }),
    body: AdminClaimReview,
    response: ClaimView,
    handler: async ({ params, body, ctx }) =>
      app.admin.reviewClaim(ctx, params.claimId, body.outcome, body.notes),
  }),
  defineRoute({
    method: 'GET',
    url: '/v1/admin/moderation',
    operationId: 'adminModerationQueue',
    summary: 'Published supplier content with instruction-like (prompt-injection) signals',
    tags: ['admin'],
    auth: 'required',
    response: z.object({ items: z.array(ClaimView.extend({ signals: z.array(z.string()) })) }),
    handler: async ({ ctx }) => ({ items: await app.admin.moderationQueue(ctx) }),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/admin/offerings/:offeringId/archive',
    operationId: 'adminArchiveOffering',
    summary: 'Moderation: remove an offering from the public catalog',
    tags: ['admin'],
    auth: 'required',
    params: z.object({ offeringId: Uuid }),
    body: z.object({ reason: z.string().min(3).max(500) }),
    response: OfferingRecord,
    handler: async ({ params, body, ctx }) => app.admin.archiveOffering(ctx, params.offeringId, body.reason),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/admin/concepts',
    operationId: 'adminAddConcept',
    summary: 'Add an ontology concept (taxonomy management)',
    tags: ['admin'],
    auth: 'required',
    body: AdminConceptCreate,
    response: z.object({ id: z.string() }),
    status: 201,
    handler: async ({ body, ctx }) => app.admin.addConcept(ctx, body),
  }),
  defineRoute({
    method: 'GET',
    url: '/v1/admin/audit',
    operationId: 'adminAuditLog',
    summary: 'Audit events (newest first)',
    tags: ['admin'],
    auth: 'required',
    query: z.object({
      organizationId: Uuid.optional(),
      action: z.string().max(100).optional(),
      limit: z.coerce.number().int().min(1).max(200).optional(),
      before: z.iso.datetime().optional(),
    }),
    response: z.object({ items: z.array(AuditEventRecord) }),
    handler: async ({ query, ctx }) => ({ items: await app.admin.auditLog(ctx, query) }),
  }),
  defineRoute({
    method: 'GET',
    url: '/v1/admin/demand-signals',
    operationId: 'adminDemandSignals',
    summary: 'Aggregated anonymized demand by concept',
    tags: ['admin'],
    auth: 'required',
    response: z.object({
      items: z.array(
        z.object({ concept: z.string(), conceptId: z.string(), requirementCount: z.number().int() }),
      ),
    }),
    handler: async ({ ctx }) => ({ items: await app.admin.demandSignals(ctx) }),
  }),
];
