import type { Application } from '@atx/application';
import {
  AssetRecord,
  CapabilityRecord,
  ClaimCreate,
  ClaimRevise,
  ClaimView,
  EvidenceCreate,
  EvidenceView,
  ExternalVideoCreate,
  OfferingCreate,
  OfferingRecord,
  OfferingStatusChange,
  OfferingUpdate,
  OrganizationCreate,
  OrganizationRecord,
  OrganizationUpdate,
  Uuid,
  VersionOnly,
  Workspace,
} from '@atx/contracts';
import { ASSET_KINDS, validationError } from '@atx/domain';
import { z } from 'zod';
import { type AnyRouteSpec, defineRoute } from '../http/route';

const org = z.object({ orgId: Uuid });
const orgOffering = z.object({ orgId: Uuid, offeringId: Uuid });
const orgClaim = z.object({ orgId: Uuid, claimId: Uuid });

/** Supplier workspace (tenant-scoped writes). Every handler authorizes via the application layer. */
export const workspaceRoutes = (app: Application): AnyRouteSpec[] => [
  defineRoute({
    method: 'POST',
    url: '/v1/organizations',
    operationId: 'createOrganization',
    summary: 'Create an organization; the caller becomes its owner',
    tags: ['workspace'],
    auth: 'required',
    body: OrganizationCreate,
    response: OrganizationRecord,
    status: 201,
    handler: async ({ body, ctx }) => app.supplier.createOrganization(ctx, body),
  }),
  defineRoute({
    method: 'PATCH',
    url: '/v1/organizations/:orgId',
    operationId: 'updateOrganization',
    summary: 'Update the organization profile (optimistic concurrency)',
    tags: ['workspace'],
    auth: 'required',
    params: org,
    body: OrganizationUpdate,
    response: OrganizationRecord,
    handler: async ({ params, body, ctx }) => app.supplier.updateOrganizationProfile(ctx, params.orgId, body),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/organizations/:orgId/verification-request',
    operationId: 'requestVerification',
    summary: 'Ask the platform to verify the organization',
    tags: ['workspace'],
    auth: 'required',
    params: org,
    response: OrganizationRecord,
    handler: async ({ params, ctx }) => app.supplier.requestVerification(ctx, params.orgId),
  }),
  defineRoute({
    method: 'GET',
    url: '/v1/organizations/:orgId/workspace',
    operationId: 'getWorkspace',
    summary: 'Owner view: offerings (all statuses), claims incl. drafts, evidence, assets',
    tags: ['workspace'],
    auth: 'required',
    params: org,
    response: Workspace,
    handler: async ({ params, ctx }) => app.supplier.listWorkspace(ctx, params.orgId),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/organizations/:orgId/offerings',
    operationId: 'createOffering',
    summary: 'Create a draft offering',
    tags: ['workspace'],
    auth: 'required',
    params: org,
    body: OfferingCreate,
    response: OfferingRecord,
    status: 201,
    handler: async ({ params, body, ctx }) => app.supplier.createOffering(ctx, params.orgId, body),
  }),
  defineRoute({
    method: 'PATCH',
    url: '/v1/organizations/:orgId/offerings/:offeringId',
    operationId: 'updateOffering',
    summary: 'Update an offering (optimistic concurrency)',
    tags: ['workspace'],
    auth: 'required',
    params: orgOffering,
    body: OfferingUpdate,
    response: OfferingRecord,
    handler: async ({ params, body, ctx }) => app.supplier.updateOffering(ctx, params.orgId, params.offeringId, body),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/organizations/:orgId/offerings/:offeringId/status',
    operationId: 'setOfferingStatus',
    summary: 'Publish, unpublish or archive an offering (explicit human action)',
    tags: ['workspace'],
    auth: 'required',
    params: orgOffering,
    body: OfferingStatusChange,
    response: OfferingRecord,
    handler: async ({ params, body, ctx }) => app.supplier.setOfferingStatus(ctx, params.orgId, params.offeringId, body.status, body.expectedVersion),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/organizations/:orgId/capabilities',
    operationId: 'createCapability',
    summary: 'Declare an organization-level capability',
    tags: ['workspace'],
    auth: 'required',
    params: org,
    body: z.object({ conceptId: z.string().max(120), name: z.string().min(2).max(160), description: z.string().max(2000).default('') }),
    response: CapabilityRecord,
    status: 201,
    handler: async ({ params, body, ctx }) => app.supplier.createCapability(ctx, params.orgId, body),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/organizations/:orgId/claims',
    operationId: 'createClaim',
    summary: 'Create a draft technical claim',
    tags: ['workspace'],
    auth: 'required',
    params: org,
    body: ClaimCreate,
    response: ClaimView,
    status: 201,
    handler: async ({ params, body, ctx }) => app.supplier.addClaim(ctx, params.orgId, body),
  }),
  defineRoute({
    method: 'PATCH',
    url: '/v1/organizations/:orgId/claims/:claimId',
    operationId: 'reviseClaim',
    summary: 'Revise a claim; substantive edits reset platform verification',
    tags: ['workspace'],
    auth: 'required',
    params: orgClaim,
    body: ClaimRevise,
    response: ClaimView,
    handler: async ({ params, body, ctx }) => app.supplier.reviseClaim(ctx, params.orgId, params.claimId, body),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/organizations/:orgId/claims/:claimId/publish',
    operationId: 'publishClaim',
    summary: 'Human review step: publish a draft claim (including AI-extracted drafts)',
    tags: ['workspace'],
    auth: 'required',
    params: orgClaim,
    body: VersionOnly,
    response: ClaimView,
    handler: async ({ params, body, ctx }) => app.supplier.publishClaim(ctx, params.orgId, params.claimId, body.expectedVersion),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/organizations/:orgId/claims/:claimId/retract',
    operationId: 'retractClaim',
    summary: 'Retract a claim',
    tags: ['workspace'],
    auth: 'required',
    params: orgClaim,
    body: VersionOnly,
    response: ClaimView,
    handler: async ({ params, body, ctx }) => app.supplier.retractClaim(ctx, params.orgId, params.claimId, body.expectedVersion),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/organizations/:orgId/evidence',
    operationId: 'createEvidence',
    summary: 'Add evidence (document reference, case study, certificate, production reference, public URL)',
    tags: ['workspace'],
    auth: 'required',
    params: org,
    body: EvidenceCreate,
    response: EvidenceView,
    status: 201,
    handler: async ({ params, body, ctx }) => app.supplier.addEvidence(ctx, params.orgId, body),
  }),
  defineRoute({
    method: 'POST',
    url: '/v1/organizations/:orgId/videos',
    operationId: 'registerExternalVideo',
    summary: 'Register an externally hosted demo video (https only; never fetched server-side)',
    tags: ['workspace'],
    auth: 'required',
    params: org,
    body: ExternalVideoCreate,
    response: AssetRecord,
    status: 201,
    handler: async ({ params, body, ctx }) => app.supplier.registerExternalVideo(ctx, params.orgId, body),
  }),
  defineRoute({
    method: 'PUT',
    url: '/v1/organizations/:orgId/assets',
    operationId: 'uploadAsset',
    summary: 'Upload a document/transcript/image (raw body). Processing (scan, extraction, AI draft) is asynchronous.',
    tags: ['workspace'],
    auth: 'required',
    params: org,
    query: z.object({
      kind: z.enum(ASSET_KINDS),
      title: z.string().min(3).max(200),
      description: z.string().max(2000).default(''),
      offeringId: Uuid.optional(),
    }),
    response: AssetRecord,
    status: 202,
    handler: async ({ params, query, ctx, request }) => {
      if (!(request.body instanceof Buffer)) throw validationError('Request body must be the raw file');
      return app.supplier.uploadAsset(ctx, params.orgId, {
        ...query,
        contentType: request.headers['content-type'] ?? '',
        bytes: new Uint8Array(request.body),
      });
    },
  }),
];
