/**
 * Generates published contract artifacts from the code that serves them:
 *   docs/api/openapi.yaml                 (HTTP API, OpenAPI 3.1)
 *   docs/api/json-schema/mcp-tools.json   (MCP tool input/output, JSON Schema 2020-12)
 * Usage: tsx scripts/generate-contracts.ts [--check]
 * --check fails (exit 1) when the committed files are out of date.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { allRoutes } from '@atx/api';
import { buildOpenApiDocument } from '@atx/api/openapi';
import { loadConfig } from '@atx/config';
import { McpTools } from '@atx/contracts';
import type { Runtime } from '@atx/runtime';
import { stringify } from 'yaml';
import { z } from 'zod';

const ROOT = path.resolve(import.meta.dirname, '..');
const check = process.argv.includes('--check');

// Route specs only need configuration at construction time; handlers are never invoked here.
const env = loadConfig({ NODE_ENV: 'development', API_PUBLIC_URL: 'https://api.atx.example', MCP_PUBLIC_URL: 'https://mcp.atx.example/mcp' });
const specOnlyRuntime = { env, app: {}, tokens: {}, pool: {}, storage: {}, assetUrls: {} } as unknown as Runtime;
const openapi = buildOpenApiDocument(allRoutes(specOnlyRuntime), env.API_PUBLIC_URL);

const toolSchemas = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  title: 'Automotive Technology Exchange MCP tool contracts',
  tools: Object.fromEntries(
    Object.entries(McpTools)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([name, contract]) => [
        name,
        {
          input: z.toJSONSchema(contract.input, { target: 'draft-2020-12', io: 'input' }),
          output: z.toJSONSchema(contract.output, { target: 'draft-2020-12', io: 'output' }),
        },
      ]),
  ),
};

const outputs: [string, string][] = [
  ['docs/api/openapi.yaml', `# GENERATED by scripts/generate-contracts.ts — do not edit by hand.\n${stringify(openapi, { lineWidth: 0 })}`],
  ['docs/api/json-schema/mcp-tools.json', `${JSON.stringify(toolSchemas, null, 2)}\n`],
];

let stale = 0;
for (const [relative, content] of outputs) {
  const file = path.join(ROOT, relative);
  if (check) {
    const current = await readFile(file, 'utf8').catch(() => '');
    if (current !== content) {
      console.error(`out of date: ${relative} (run pnpm contracts:generate)`);
      stale += 1;
    }
  } else {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, content);
    console.log(`wrote ${relative}`);
  }
}
if (stale > 0) process.exit(1);
